workflows:
  runpad-codemagic-example-ios:
    name: Runpad Codemagic Example iOS
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - runpad-credentials # <-- RUNPAD_CLIENT_ID and RUNPAD_CLIENT_SECRET must be configured as Secure environment variables in this group on Codemagic
        - runpad-options     # <-- RUNPAD_PROJECT_ID, RUNPAD_DEVICE must be configured as environment variables in this group on Codemagic
      xcode: latest          # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
    scripts:
      - name: Build .app simulator build
        script: |
          DERIVED_DATA_PATH=/tmp/runpad-codemagic-example-ios-$(uuidgen)

          xcodebuild clean build                                       \
            -scheme runpad-codemagic-example-ios                       \
            -project runpad-codemagic-example-ios.xcodeproj            \
            -configuration Release                                     \
            -destination 'generic/platform=iOS Simulator'              \
            -derivedDataPath "$DERIVED_DATA_PATH"                      \
            clean build

          echo "APP_DIR_PATH=${DERIVED_DATA_PATH}/Build/Products/Release-iphonesimulator/runpad-codemagic-example-ios.app" >>$CM_ENV
      - name: Runpad - Install Runpad CLI
        script: |
          curl -fsSL https://downloads.bytesalt.com/runpad-cli-install.sh | bash
      - name: Runpad - Run tests
        script: |
          runpad run                                            \
          --project-id=$RUNPAD_PROJECT_ID                       \
          --platform=ios                                        \
          --device="$RUNPAD_DEVICE"                             \
          --build-path=$APP_DIR_PATH
    artifacts:
      - $APP_DIR_PATH
      - $HOME/.runpad/logs/*
